@echo off
echo Deteniendo todos los procesos del chat...
echo Deteniendo servidor y clientes...
taskkill /F /IM java.exe
echo Limpiando archivos temporales...
del chat_messages.txt 2>nul
del connected_users.txt 2>nul
echo Procesos detenidos y archivos limpiados. Presione cualquier tecla para salir...
pause > nul 